---
- name: Transfer and execute sumo-install script
  # Use host name from your ~/.ssh/config referenced in /etc/ansible/hosts
  # README File with more info in ../scripts/README.md
  # hosts: prod-api-ecs
  hosts: all
  user: ec2-user

  tasks:
     - name: Transfer Vars Script
       copy: src=./scripts/sumo-vars.sh dest=/home/ec2-user mode=0775

     - name: Copy and Execute the script 
       script: ./scripts/sumo-install.sh

  # Execute by running this cmd (Where -i is your host name:
  # ansible-playbook -i host-name, -e ansible_network_os=vyos sumo-install.yml
