---
- name: Transfer and execute sumo-remove script
  # Use host name from your ~/.ssh/config referenced in /etc/ansible/hosts
  # README File with more info in ../scripts/README.md
  # hosts: host-name
  hosts: all
  user: ec2-user

  tasks:

     - name: Copy and Execute the script 
       script: ./scripts/sumo-remove.sh

 # Execute by running this cmd (Where -i is your host name:
 # ansible-playbook -i host-name, -e ansible_network_os=vyos sumo-remove.yml
